### ISSUE TITLE
question about the firmware usage?

### ISSUE THREAD

**Issue by lj-cug** [dev-0x7C6/kinect-audio-setup#2]
Dear Developers:
    I have a question about the usage of kinect-audio-setup. Now I have installed this tool in my Ubuntu laptop and can listen the audio from my Kinect ONE camera. The audio I obtained from Kinect is through the Kinect SDK's algorihm like noise suppresion, gain control  etc., isn't it? Because I cannot conduct the audio-processing algorithms in the firmware by myself like the tutorials in Windows SDK using C# and C++, I get confused about this. Thanks!
Kinect Audio SDK setup in Windows is following:
API                              Default setup:
![image](https://user-images.githubusercontent.com/53997605/149722681-07c50c0e-72ea-49e2-a0eb-d026ec8935f8.png)

**Comment by dev-0x7C6** [comment]
Well I'm maintaining this project only for hosting proposes / build system. I think this extracted firmware is only for making kinect on linux platform be detected as microphone device, but I can be wrong.
